ALTER TABLE test_message ADD COLUMN prep_message_original_response TEXT;
ALTER TABLE test_message ADD COLUMN result_store_status VARCHAR(250);

CREATE TABLE transport_analysis (
  transport_analysis_id          INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  connection_label               VARCHAR(250) NOT NULL,
  transport_type                 VARCHAR(250) NOT NULL,
  analysis_notes                 TEXT,
  report_complete                VARCHAR(250)
);

CREATE TABLE transport_wsdl_cdc (
  transport_wsdl_cdc_id          INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  transport_analysis_id          INTEGER NOT NULL,
  transport_status               VARCHAR(250),
  transport_notes                TEXT,
  pass_eye_test                  VARCHAR(250),
  client_certificate             VARCHAR(250),
  ct_supports                    VARCHAR(250),
  ct_conforms                    VARCHAR(250),
  ct_failure_reason              TEXT,
  ssm_supports                   VARCHAR(250),
  ssm_conforms                   VARCHAR(250),
  ssm_failure_reason             TEXT,
  sf_supports                    VARCHAR(250),
  sf_conforms                    VARCHAR(250),
  sf_failure_reason              TEXT
);

CREATE TABLE transport_other (
  transport_other_id             INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  transport_analysis_id          INTEGER NOT NULL,
  client_certificate             VARCHAR(250),
  operation                      VARCHAR(250),
  username                       VARCHAR(250),
  password                       VARCHAR(250),
  facilityid                     VARCHAR(250),
  other_parameter                VARCHAR(250),
  hl7_message                    VARCHAR(250),
  could_use_cdc_wsdl             VARCHAR(250),
  findings_report                VARCHAR(250)
);



insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (1, "AK VacTraAK", "CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (2, "AL ImmPRINT", "Non-CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (3, "AR WebIZ", "Non-CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (4, "AZ ASIIS", "Non-CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (5, "CA Imperial", "Researched/Interviewed", "Unable to determine.", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (6, "CA CAIR", "CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (7, "CA SDIR", "Post", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (8, "CA RIDE", "Non-participator CDC WSDL", "", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (9, "CO CIIS", "CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (10, "CT CIRTS", "Researched/Interviewed", "No POST or SOAP. Current IIS only offers PHINMS. ", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (11, "DC", "Researched/Interviewed", "Unable to determine.", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (12, "DE DelVAX", "Non-CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (13, "Envision Dev Testing", "Non-CDC WSDL", "", "NIST Provided");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (14, "FL SHOTS", "Non-participator CDC WSDL", "", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (15, "GA GRITS", "CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (16, "HI HIR", "CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (17, "IA IRIS", "CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (18, "ID IRIS", "CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (19, "IL I-CARE", "Non-CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (20, "IN CHIRP", "Post", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (21, "KS WebIZ", "Non-CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (22, "KY KYIR", "Non-CDC WSDL", "", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (23, "LA LINKS", "Non-participator CDC WSDL", "", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (24, "MA MIIS", "CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (25, "MD IMMUNET", "CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (26, "ME PHCHUB", "CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (27, "MI MCIR", "Researched/Interviewed", "Unable to determine.  MiHIN didn't have specifics.  Mention of VPN requirements", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (28, "MN MIIC WS Test", "CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (29, "MO ShowMeVax", "Non-CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (30, "MS MIIX (IHS only)", "Researched/Interviewed", "Has CDC WSDL per Brandy; I can find a POST endpoint", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (31, "MT imMTrax", "CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (32, "NC NCIR", "CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (33, "ND SIIS", "CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (34, "NE NESIIS", "CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (35, "NH", "Researched/Interviewed", "No POST or SOAP.  Will have STC PHCHub if/when go live.", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (36, "NJ SIIS", "Non-CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (37, "NM NMSIIS", "Post", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (38, "NV WebIZ", "Post", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (39, "NY NYSIIS", "Researched/Interviewed", "Working Towards Soap. Per Vendor", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (40, "NY CIR", "CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (41, "OH ImpactSIIS", "Non-CDC WSDL", "", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (42, "OK OSIIS", "Researched/Interviewed", "No POST or SOAP.  Uses PHINMS.", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (43, "OR ALERT", "Non-CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (44, "PA SIIS", "Post", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (45, "PA PHIL", "Non-CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (46, "PI: Amercian Samoa", "Researched/Interviewed", "Unable to determine.", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (47, "Guam", "Researched/Interviewed", "Unable to determine.", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (48, "PI: Marshall Islands", "Researched/Interviewed", "Unable to determine.", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (49, "PI: Micronesia", "Researched/Interviewed", "Unable to determine.", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (50, "PI: N. Mariana Islands", "Researched/Interviewed", "Unable to determine.", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (51, "PI: Palau", "Researched/Interviewed", "Unable to determine.", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (52, "PR PRIR", "Researched/Interviewed", "Working Towards Soap. Per Vendor", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (53, "RI KIDSNET", "CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (54, "SC", "Researched/Interviewed", "Has POST - No Details.", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (55, "SD SDIIS", "Post", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (56, "STC Epicenter - Demo PHC Hub", "CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (57, "TN TIR", "Researched/Interviewed", "Has Soap - No Details.  Async by Basic Auth over SSL", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (58, "TX ImmTrac", "Researched/Interviewed", "Working Towards Soap. Per Vendor", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (59, "TX SAIRS", "Researched/Interviewed", "Has Soap - No Details.  Found reference in HL7 Guide", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (60, "UT USIIS", "Researched/Interviewed", "Has Soap - No Details on web", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (61, "VA VIIS", "CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (62, "Virgin Islands", "Researched/Interviewed", "Unable to determine.", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (63, "VT", "Researched/Interviewed", "Unable to determine.  Through VHIE.", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (64, "WA", "CDC WSDL", "", "Yes");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (65, "WI WIR", "Researched/Interviewed", "Has CDC WSDL per HP", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (66, "WV", "Researched/Interviewed", "Has CDC WSDL per Brandy; I can find a POST endpoint", "");
insert into transport_analysis (transport_analysis_id, connection_label, transport_type, analysis_notes, report_complete) VALUES (67, "WY WyIR", "CDC WSDL", "", "Yes");


insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (2, "Done", "Done", "No", "-", "-", "-", "", "-", "-", "", "-", "-", "");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (1, "Done", "Done", "Yes", "No", "Yes", "Yes", "", "Yes", "Yes", "", "Yes", "No", "Close.  It throws a securityFault, but not in the way defined by the CDC WSDL.");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (6, "Done", "Done", "Yes", "Yes", "Yes", "Yes", "", "Yes", "Yes", "", "Yes", "No", "I received a fault, but according to NIST it didn't validate per the CDC WSDL.");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (9, "Done", "Done", "Yes", "No", "Yes", "Yes", "", "Yes", "Yes", "", "Yes", "Yes", "Not according to NIST.  CO used ""AUTHENTICATION_FAILED"" where it should have used ""Security"".  They are very close as compared to others.");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (13, "Done", "Done", "No", "-", "-", "-", "WSDL provided does not define a ConnectivityTest Operation", "-", "-", "WSDL provided does not define a SubmitSingleMessage Operation", "-", "-", "");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (15, "Done", "Done", "Yes", "No", "Yes", "Yes", "", "Yes", "Yes", "", "Yes", "No", "Does not throw Fault.  Returns free text where HL7 ACK is supposed to go.");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (16, "Done", "Done", "Yes", "Yes", "Yes", "Yes", "", "Yes", "Yes", "", "Yes", "No", "Does not throw Fault.  Returns free text where HL7 ACK is supposed to go.");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (17, "Done", "Done", "Yes", "Yes", "Yes", "Yes", "", "Yes", "Yes", "", "Yes", "No", "Throws fault, but it doesn't conform");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (18, "Done", "Done", "Yes", "Yes", "Yes", "Yes", "", "Yes", "Yes", "", "Yes", "No", "Does not throw Fault.  Returns free text where HL7 ACK is supposed to go.");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (19, "Done", "Done", "No", "-", "-", "-", "WSDL provided does not define a ConnectivityTest Operation", "-", "-", "WSDL provided does not define a SubmitSingleMessage Operation", "-", "-", "WSDL provided does not define a SecurityFault");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (21, "Done", "Done", "No", "-", "-", "-", "WSDL provided does not define a ConnectivityTest Operation", "-", "-", "WSDL provided does not define a SubmitSingleMessage Operation", "-", "-", "WSDL provided does not define a SecurityFault");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (24, "Done", "Done", "Yes", "No", "Yes", "No", "Authenciation is required and parameters in header through WS-Security", "Yes", "No", "Authentication parameters in header through WS-Security. Password and HL7 message must be base64 encoded. Response is good according to NIST, but it must be base64 decoded.", "No", "No", "");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (25, "Done", "Done", "Yes", "No", "Yes", "Yes", "", "Yes", "Yes", "", "Yes", "No", "Does not throw Fault.  Returns free text where HL7 ACK is supposed to go.");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (26, "Done", "Done", "Yes", "No", "Yes", "Yes", "", "Yes", "Yes", "", "Yes", "No", "Close.  It throws a securityFault, but not in the way defined by the CDC WSDL.");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (28, "Done", "Done", "Yes", "No", "Yes", "Yes", "", "Yes", "Yes", "", "Yes", "No", "Does not throw Fault.  Returns free text where HL7 ACK is supposed to go.");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (31, "Done", "Done", "Yes", "No", "Yes", "Yes", "", "Yes", "Yes", "", "Yes", "No", "Close.  It throws a securityFault, but not in the way defined by the CDC WSDL.");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (32, "Done", "Done", "Yes", "Yes", "Yes", "Yes", "", "Yes", "Yes", "", "Yes", "Yes", "Not according to NIST.  NCIR used ""Security Fault"" where it should have used ""Security"".  They are very close as compared to others.");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (34, "Done", "Done", "Yes", "No", "Yes", "Yes", "", "Yes", "Yes", "", "Yes", "No", "Close.  It throws a securityFault, but not in the way defined by the CDC WSDL.");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (33, "Done", "Done", "Yes", "Yes", "Yes", "No", "targetNamespace was changed from urn:cdc:iisb:2011 to https://ndiisioptest.noridian.com/. ", "Yes", "No", "targetNamespace was changed from urn:cdc:iisb:2011 to https://ndiisioptest.noridian.com/. ", "No", "No", "WSDL provided does not define a SecurityFault");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (40, "Done", "Done", "Yes", "No", "Yes", "Yes", "", "Yes", "Yes", "", "Yes", "Yes", "Not according to NIST.  One value was off.  A longer text description was used where according to the specification ""Security"" should have been used. Very minor. They are very close as compared to others.");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (43, "Done", "Done", "No", "-", "-", "-", "WSDL provided does not define a ConnectivityTest Operation", "-", "-", "WSDL provided does not define a SubmitSingleMessage Operation", "-", "-", "WSDL provided does not define a SecurityFault");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (45, "Done", "Done", "No", "-", "-", "-", "WSDL provided does not define a ConnectivityTest Operation", "-", "-", "WSDL provided does not define a SubmitSingleMessage Operation", "-", "-", "WSDL provided does not define a SecurityFault");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (53, "Done", "Done", "Yes", "No", "Yes", "Yes", "", "Yes", "Yes", "", "Yes", "No", "Does not throw Fault.  Returns Structured HL7 ACK message with AR");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (56, "Done", "Done", "Yes", "No", "Yes", "Yes", "", "Yes", "Yes", "", "Yes", "No", "Close.  It throws a securityFault, but not in the way defined by the CDC WSDL.");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (61, "Done", "Done", "Yes", "No", "Yes", "Yes", "", "Yes", "Yes", "", "Yes", "No", "Does not throw Fault.  Returns free text where HL7 ACK is supposed to go.");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (64, "Done", "Done", "Yes", "No", "Yes", "Yes", "", "Yes", "Yes", "", "Yes", "No", "Close.  It throws a securityFault, but not in the way defined by the CDC WSDL.");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (67, "Done", "Done", "Yes", "No", "Yes", "Yes", "", "Yes", "Yes", "", "Yes", "No", "Close.  It throws a securityFault, but not in the way defined by the CDC WSDL.");

insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (14, "Done", "Done", "Yes", "Couldn't Confirm", "Yes", "No", "Requires User and Password.  Operation signature is different", "Yes", "Can't Confirm", "", "Yes", "Can't Confirm", "");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (8, "Done", "Done", "Yes", "No", "Yes", "Can't Confirm", "", "Yes", "Can't Confirm", "", "Yes", "Can't Confirm", "");
insert into transport_wsdl_cdc (transport_analysis_id, transport_status, transport_notes, pass_eye_test, client_certificate, ct_supports, ct_conforms, ct_failure_reason, ssm_supports, ssm_conforms, ssm_failure_reason, sf_supports, sf_conforms, sf_failure_reason) VALUES (23, "Done", "Done", "Yes", "No", "Yes", "Can't Confirm", "", "Yes", "Can't Confirm", "", "Yes", "Can't Confirm", "");


insert into transport_other (transport_analysis_id, client_certificate, operation, username, password, facilityid, other_parameter, hl7_message, could_use_cdc_wsdl, findings_report) VALUES (2, "Yes", "aliishl7", "None", "None", "None", "None", "Parameter in Operation", "Yes", "1");
insert into transport_other (transport_analysis_id, client_certificate, operation, username, password, facilityid, other_parameter, hl7_message, could_use_cdc_wsdl, findings_report) VALUES (3, "No", "executeHL7Message", "Parameter in Operation", "Parameter in Operation", "None", "None", "Parameter in Operation", "Yes", "2");
insert into transport_other (transport_analysis_id, client_certificate, operation, username, password, facilityid, other_parameter, hl7_message, could_use_cdc_wsdl, findings_report) VALUES (4, "No", "Sync_Submit", "Parameter in Operation", "Parameter in Operation", "None", "None", "Parameter in Operation", "Yes", "R2");
insert into transport_other (transport_analysis_id, client_certificate, operation, username, password, facilityid, other_parameter, hl7_message, could_use_cdc_wsdl, findings_report) VALUES (12, "No", "executeHL7Message", "Parameter in Operation", "Parameter in Operation", "None", "None", "Parameter in Operation", "Yes", "3");
insert into transport_other (transport_analysis_id, client_certificate, operation, username, password, facilityid, other_parameter, hl7_message, could_use_cdc_wsdl, findings_report) VALUES (13, "No", "executeHL7Message", "Parameter in Operation", "Parameter in Operation", "None", "None", "Parameter in Operation", "Yes", "4");
insert into transport_other (transport_analysis_id, client_certificate, operation, username, password, facilityid, other_parameter, hl7_message, could_use_cdc_wsdl, findings_report) VALUES (19, "No", "HL7Request", "Parameter in Operation", "Parameter in Operation", "None", "None", "Parameter in Operation", "Yes", "5");
insert into transport_other (transport_analysis_id, client_certificate, operation, username, password, facilityid, other_parameter, hl7_message, could_use_cdc_wsdl, findings_report) VALUES (21, "No", "ProcessHL7Message", "Parameter in Operation", "Parameter in Operation", "None", "None", "Parameter in Operation", "Yes", "6");
insert into transport_other (transport_analysis_id, client_certificate, operation, username, password, facilityid, other_parameter, hl7_message, could_use_cdc_wsdl, findings_report) VALUES (22, "No", "executeHL7Message", "Parameter in Operation", "Parameter in Operation", "None", "None", "Parameter in Operation", "Yes", "R2");
insert into transport_other (transport_analysis_id, client_certificate, operation, username, password, facilityid, other_parameter, hl7_message, could_use_cdc_wsdl, findings_report) VALUES (29, "No", "No Operation - all in header", "Proprietary (In Header)", "Proprietary (In Header)", "Proprietary (In Header)", "Proprietary (In Header) 2nd Password", "Proprietary (In Header)", "No", "7");
insert into transport_other (transport_analysis_id, client_certificate, operation, username, password, facilityid, other_parameter, hl7_message, could_use_cdc_wsdl, findings_report) VALUES (36, "No", "NJIISIMSPutRequest", "Parameter in Operation", "Parameter in Operation", "Parameter in Operation", "HL7 Version as parameter in Operation", "Parameter in Operation", "Yes", "8");
insert into transport_other (transport_analysis_id, client_certificate, operation, username, password, facilityid, other_parameter, hl7_message, could_use_cdc_wsdl, findings_report) VALUES (41, "No", "SubmitSingleVXUMessage", "Parameter in Operation", "Parameter in Operation", "Parameter in Operation", "None", "Parameter in Operation", "Yes", "9");
insert into transport_other (transport_analysis_id, client_certificate, operation, username, password, facilityid, other_parameter, hl7_message, could_use_cdc_wsdl, findings_report) VALUES (43, "Yes", "UpdateHistory", "WS-Security (In Header)", "WS-Security (In Header)", "None", "None", "Parameter in Operation", "Yes", "10");
insert into transport_other (transport_analysis_id, client_certificate, operation, username, password, facilityid, other_parameter, hl7_message, could_use_cdc_wsdl, findings_report) VALUES (45, "No", "executeHL7Message", "Parameter in Operation", "Parameter in Operation", "None", "None", "Parameter in Operation", "Yes", "11");

insert into transport_other (transport_analysis_id, client_certificate, operation, username, password, facilityid, other_parameter, hl7_message, could_use_cdc_wsdl, findings_report) VALUES (7, "No", "POST", "Yes", "Yes", "Yes", "No", "Yes", "Yes", "1");
insert into transport_other (transport_analysis_id, client_certificate, operation, username, password, facilityid, other_parameter, hl7_message, could_use_cdc_wsdl, findings_report) VALUES (20, "No", "POST", "Yes", "Yes", "No", "No", "Yes", "Yes", "2");
insert into transport_other (transport_analysis_id, client_certificate, operation, username, password, facilityid, other_parameter, hl7_message, could_use_cdc_wsdl, findings_report) VALUES (37, "No", "POST", "Yes", "Yes", "Yes", "No", "Yes", "Yes", "3");
insert into transport_other (transport_analysis_id, client_certificate, operation, username, password, facilityid, other_parameter, hl7_message, could_use_cdc_wsdl, findings_report) VALUES (38, "No", "POST", "Yes - Called userName", "Yes - Called password", "No", "No", "Yes - Called flatWire", "Yes", "4");
insert into transport_other (transport_analysis_id, client_certificate, operation, username, password, facilityid, other_parameter, hl7_message, could_use_cdc_wsdl, findings_report) VALUES (55, "No", "POST", "Yes", "Yes", "Yes", "No", "Yes", "Yes", "R2");
insert into transport_other (transport_analysis_id, client_certificate, operation, username, password, facilityid, other_parameter, hl7_message, could_use_cdc_wsdl, findings_report) VALUES (44, "No", "POST", "Yes", "Yes", "Yes", "No", "Yes", "Yes", "5");
