package org.openimmunizationsoftware.dqa.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6-redhat-1
 * 2013-10-23T16:32:43.536-04:00
 * Generated source version: 2.4.6-redhat-1
 * 
 */
@WebService(targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", name = "DqaServiceSOAPImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface DqaServiceSOAPImpl {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "submitMessage", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.SubmitMessage")
    @WebMethod
    @ResponseWrapper(localName = "submitMessageResponse", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.SubmitMessageResponse")
    public org.openimmunizationsoftware.dqa.service.client.SubmitMessageResultType submitMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        org.openimmunizationsoftware.dqa.service.client.SubmitMessageType arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBatchIssueList", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetBatchIssueList")
    @WebMethod
    @ResponseWrapper(localName = "getBatchIssueListResponse", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetBatchIssueListResponse")
    public org.openimmunizationsoftware.dqa.service.client.GetBatchIssueListResultType getBatchIssueList(
        @WebParam(name = "arg0", targetNamespace = "")
        org.openimmunizationsoftware.dqa.service.client.GetBatchIssueListType arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBatchCodeReceivedList", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetBatchCodeReceivedList")
    @WebMethod
    @ResponseWrapper(localName = "getBatchCodeReceivedListResponse", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetBatchCodeReceivedListResponse")
    public org.openimmunizationsoftware.dqa.service.client.GetBatchCodeReceivedListResultType getBatchCodeReceivedList(
        @WebParam(name = "arg0", targetNamespace = "")
        org.openimmunizationsoftware.dqa.service.client.GetBatchCodeReceivedListType arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateCodeReceived", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.UpdateCodeReceived")
    @WebMethod
    @ResponseWrapper(localName = "updateCodeReceivedResponse", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.UpdateCodeReceivedResponse")
    public org.openimmunizationsoftware.dqa.service.client.UpdateCodeReceivedResultType updateCodeReceived(
        @WebParam(name = "arg0", targetNamespace = "")
        org.openimmunizationsoftware.dqa.service.client.UpdateCodeReceivedType arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBatchDqaReport", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetBatchDqaReport")
    @WebMethod
    @ResponseWrapper(localName = "getBatchDqaReportResponse", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetBatchDqaReportResponse")
    public org.openimmunizationsoftware.dqa.service.client.GetBatchDqaReportResultType getBatchDqaReport(
        @WebParam(name = "arg0", targetNamespace = "")
        org.openimmunizationsoftware.dqa.service.client.GetBatchDqaReportType arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateSubmitterProfile", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.UpdateSubmitterProfile")
    @WebMethod
    @ResponseWrapper(localName = "updateSubmitterProfileResponse", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.UpdateSubmitterProfileResponse")
    public org.openimmunizationsoftware.dqa.service.client.UpdateSubmitterProfileResultType updateSubmitterProfile(
        @WebParam(name = "arg0", targetNamespace = "")
        org.openimmunizationsoftware.dqa.service.client.UpdateSubmitterProfileType arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMessageReceivedList", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetMessageReceivedList")
    @WebMethod
    @ResponseWrapper(localName = "getMessageReceivedListResponse", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetMessageReceivedListResponse")
    public org.openimmunizationsoftware.dqa.service.client.GetMessageReceivedListResultType getMessageReceivedList(
        @WebParam(name = "arg0", targetNamespace = "")
        org.openimmunizationsoftware.dqa.service.client.GetMessageReceivedListType arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBatchReport", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetBatchReport")
    @WebMethod
    @ResponseWrapper(localName = "getBatchReportResponse", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetBatchReportResponse")
    public org.openimmunizationsoftware.dqa.service.client.GetBatchReportResultType getBatchReport(
        @WebParam(name = "arg0", targetNamespace = "")
        org.openimmunizationsoftware.dqa.service.client.GetBatchReportType arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBatchActionList", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetBatchActionList")
    @WebMethod
    @ResponseWrapper(localName = "getBatchActionListResponse", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetBatchActionListResponse")
    public org.openimmunizationsoftware.dqa.service.client.GetBatchActionListResultType getBatchActionList(
        @WebParam(name = "arg0", targetNamespace = "")
        org.openimmunizationsoftware.dqa.service.client.GetBatchActionListType arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBatch", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetBatch")
    @WebMethod
    @ResponseWrapper(localName = "getBatchResponse", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetBatchResponse")
    public org.openimmunizationsoftware.dqa.service.client.GetBatchResultType getBatch(
        @WebParam(name = "arg0", targetNamespace = "")
        org.openimmunizationsoftware.dqa.service.client.GetBatchType arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createMessageBatch", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.CreateMessageBatch")
    @WebMethod
    @ResponseWrapper(localName = "createMessageBatchResponse", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.CreateMessageBatchResponse")
    public org.openimmunizationsoftware.dqa.service.client.CreateMessageBatchResultType createMessageBatch(
        @WebParam(name = "arg0", targetNamespace = "")
        org.openimmunizationsoftware.dqa.service.client.CreateMessageBatchType arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPatient", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetPatient")
    @WebMethod
    @ResponseWrapper(localName = "getPatientResponse", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetPatientResponse")
    public org.openimmunizationsoftware.dqa.service.client.GetPatientResultType getPatient(
        @WebParam(name = "arg0", targetNamespace = "")
        org.openimmunizationsoftware.dqa.service.client.GetPatientType arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getNextOfKinList", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetNextOfKinList")
    @WebMethod
    @ResponseWrapper(localName = "getNextOfKinListResponse", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetNextOfKinListResponse")
    public org.openimmunizationsoftware.dqa.service.client.GetNextOfKinListResultType getNextOfKinList(
        @WebParam(name = "arg0", targetNamespace = "")
        org.openimmunizationsoftware.dqa.service.client.GetNextOfKinListType arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPotentialIssueStatusList", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetPotentialIssueStatusList")
    @WebMethod
    @ResponseWrapper(localName = "getPotentialIssueStatusListResponse", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetPotentialIssueStatusListResponse")
    public org.openimmunizationsoftware.dqa.service.client.GetPotentialIssueStatusListResultType getPotentialIssueStatusList(
        @WebParam(name = "arg0", targetNamespace = "")
        org.openimmunizationsoftware.dqa.service.client.GetPotentialIssueStatusListType arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSubmitterProfile", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetSubmitterProfile")
    @WebMethod
    @ResponseWrapper(localName = "getSubmitterProfileResponse", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetSubmitterProfileResponse")
    public org.openimmunizationsoftware.dqa.service.client.GetSubmitterProfileResultType getSubmitterProfile(
        @WebParam(name = "arg0", targetNamespace = "")
        org.openimmunizationsoftware.dqa.service.client.GetSubmitterProfileType arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updatePotentialIssueStatus", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.UpdatePotentialIssueStatus")
    @WebMethod
    @ResponseWrapper(localName = "updatePotentialIssueStatusResponse", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.UpdatePotentialIssueStatusResponse")
    public org.openimmunizationsoftware.dqa.service.client.UpdatePotentialIssueStatusResultType updatePotentialIssueStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        org.openimmunizationsoftware.dqa.service.client.UpdatePotentialIssueStatusType arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBatches", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetBatches")
    @WebMethod
    @ResponseWrapper(localName = "getBatchesResponse", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetBatchesResponse")
    public org.openimmunizationsoftware.dqa.service.client.GetBatchesResultType getBatches(
        @WebParam(name = "arg0", targetNamespace = "")
        org.openimmunizationsoftware.dqa.service.client.GetBatchesType arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBatchVaccineCvxList", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetBatchVaccineCvxList")
    @WebMethod
    @ResponseWrapper(localName = "getBatchVaccineCvxListResponse", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetBatchVaccineCvxListResponse")
    public org.openimmunizationsoftware.dqa.service.client.GetBatchVaccineCvxListResultType getBatchVaccineCvxList(
        @WebParam(name = "arg0", targetNamespace = "")
        org.openimmunizationsoftware.dqa.service.client.GetBatchVaccineCvxListType arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMessageReceivedDetails", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetMessageReceivedDetails")
    @WebMethod
    @ResponseWrapper(localName = "getMessageReceivedDetailsResponse", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetMessageReceivedDetailsResponse")
    public org.openimmunizationsoftware.dqa.service.client.GetMessageReceivedDetailsResultType getMessageReceivedDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        org.openimmunizationsoftware.dqa.service.client.GetMessageReceivedDetailsType arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getReportTemplates", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetReportTemplates")
    @WebMethod
    @ResponseWrapper(localName = "getReportTemplatesResponse", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetReportTemplatesResponse")
    public org.openimmunizationsoftware.dqa.service.client.GetReportTemplatesResultType getReportTemplates(
        @WebParam(name = "arg0", targetNamespace = "")
        org.openimmunizationsoftware.dqa.service.client.GetReportTemplatesType arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCodeReceivedList", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetCodeReceivedList")
    @WebMethod
    @ResponseWrapper(localName = "getCodeReceivedListResponse", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetCodeReceivedListResponse")
    public org.openimmunizationsoftware.dqa.service.client.GetCodeReceivedListResultType getCodeReceivedList(
        @WebParam(name = "arg0", targetNamespace = "")
        org.openimmunizationsoftware.dqa.service.client.GetCodeReceivedListType arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVaccinationList", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetVaccinationList")
    @WebMethod
    @ResponseWrapper(localName = "getVaccinationListResponse", targetNamespace = "http://dqaws.openimmunizationsoftware.org/dqa/", className = "org.openimmunizationsoftware.dqa.service.client.GetVaccinationListResponse")
    public org.openimmunizationsoftware.dqa.service.client.GetVaccinationListResultType getVaccinationList(
        @WebParam(name = "arg0", targetNamespace = "")
        org.openimmunizationsoftware.dqa.service.client.GetVaccinationListType arg0
    );
}
