/**
 * DqaService_PortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package org.openimmunizationsoftware.dqa.service.client;

public interface DqaService_PortType extends java.rmi.Remote {
    public org.openimmunizationsoftware.dqa.service.client.SubmitMessageResultType submitMessage(org.openimmunizationsoftware.dqa.service.client.SubmitMessageType submitMessageRequest) throws java.rmi.RemoteException, org.openimmunizationsoftware.dqa.service.client.FaultType;
    public org.openimmunizationsoftware.dqa.service.client.GetBatchesResultType getBatches(org.openimmunizationsoftware.dqa.service.client.GetBatchesType getBatchesRequest) throws java.rmi.RemoteException, org.openimmunizationsoftware.dqa.service.client.FaultType;
    public org.openimmunizationsoftware.dqa.service.client.GetBatchDqaReportResultType getBatchDqaReport(org.openimmunizationsoftware.dqa.service.client.GetBatchDqaReportType getBatchDqaReportRequest) throws java.rmi.RemoteException, org.openimmunizationsoftware.dqa.service.client.FaultType;
    public org.openimmunizationsoftware.dqa.service.client.CreateMessageBatchResultType createMessageBatch(org.openimmunizationsoftware.dqa.service.client.CreateMessageBatchType createMessageBatchRequest) throws java.rmi.RemoteException, org.openimmunizationsoftware.dqa.service.client.FaultType;
    public org.openimmunizationsoftware.dqa.service.client.UpdateSubmitterProfileResultType updateSubmitterProfile(org.openimmunizationsoftware.dqa.service.client.UpdateSubmitterProfileType updateSubmitterProfileRequest) throws java.rmi.RemoteException, org.openimmunizationsoftware.dqa.service.client.FaultType;
    public org.openimmunizationsoftware.dqa.service.client.GetSubmitterProfileResultType getSubmitterProfile(org.openimmunizationsoftware.dqa.service.client.GetSubmitterProfileType getSubmitterProfileRequest) throws java.rmi.RemoteException, org.openimmunizationsoftware.dqa.service.client.FaultType;
    public org.openimmunizationsoftware.dqa.service.client.GetReportTemplatesResultType getReportTemplates(org.openimmunizationsoftware.dqa.service.client.GetReportTemplatesType getReportTemplatesRequest) throws java.rmi.RemoteException, org.openimmunizationsoftware.dqa.service.client.FaultType;
    public org.openimmunizationsoftware.dqa.service.client.GetCodeReceivedListResultType getCodeReceivedList(org.openimmunizationsoftware.dqa.service.client.GetCodeReceivedListType getCodeReceivedListRequest) throws java.rmi.RemoteException, org.openimmunizationsoftware.dqa.service.client.FaultType;
    public org.openimmunizationsoftware.dqa.service.client.UpdateCodeReceivedResultType updateCodeReceived(org.openimmunizationsoftware.dqa.service.client.UpdateCodeReceivedType updateCodeReceivedRequest) throws java.rmi.RemoteException, org.openimmunizationsoftware.dqa.service.client.FaultType;
    public org.openimmunizationsoftware.dqa.service.client.GetPotentialIssueStatusListResultType getPotentialIssueStatusList(org.openimmunizationsoftware.dqa.service.client.GetPotentialIssueStatusListType getPotentialIssueStatusListRequest) throws java.rmi.RemoteException, org.openimmunizationsoftware.dqa.service.client.FaultType;
    public org.openimmunizationsoftware.dqa.service.client.UpdatePotentialIssueStatusResultType updatePotentialIssueStatus(org.openimmunizationsoftware.dqa.service.client.UpdatePotentialIssueStatusType updatePotentialIssueStatusRequest) throws java.rmi.RemoteException, org.openimmunizationsoftware.dqa.service.client.FaultType;
    public org.openimmunizationsoftware.dqa.service.client.GetBatchResultType getBatch(org.openimmunizationsoftware.dqa.service.client.GetBatchType getBatchRequest) throws java.rmi.RemoteException, org.openimmunizationsoftware.dqa.service.client.FaultType;
    public org.openimmunizationsoftware.dqa.service.client.GetBatchIssueListResultType getBatchIssueList(org.openimmunizationsoftware.dqa.service.client.GetBatchIssueListType getBatchIssueListRequest) throws java.rmi.RemoteException, org.openimmunizationsoftware.dqa.service.client.FaultType;
    public org.openimmunizationsoftware.dqa.service.client.GetBatchReportResultType getBatchReport(org.openimmunizationsoftware.dqa.service.client.GetBatchReportType getBatchReportRequest) throws java.rmi.RemoteException, org.openimmunizationsoftware.dqa.service.client.FaultType;
    public org.openimmunizationsoftware.dqa.service.client.GetBatchActionListResultType getBatchActionList(org.openimmunizationsoftware.dqa.service.client.GetBatchActionListType getBatchActionListRequest) throws java.rmi.RemoteException, org.openimmunizationsoftware.dqa.service.client.FaultType;
    public org.openimmunizationsoftware.dqa.service.client.GetBatchVaccineCvxListResultType getBatchVaccineCvxList(org.openimmunizationsoftware.dqa.service.client.GetBatchVaccineCvxListType getBatchVaccineCvxListRequest) throws java.rmi.RemoteException, org.openimmunizationsoftware.dqa.service.client.FaultType;
    public org.openimmunizationsoftware.dqa.service.client.GetBatchCodeReceivedListResultType getBatchCodeReceivedList(org.openimmunizationsoftware.dqa.service.client.GetBatchCodeReceivedListType getBatchCodeReceivedListRequest) throws java.rmi.RemoteException, org.openimmunizationsoftware.dqa.service.client.FaultType;
    public org.openimmunizationsoftware.dqa.service.client.GetMessageReceivedListResultType getMessageReceivedList(org.openimmunizationsoftware.dqa.service.client.GetMessageReceivedListType getMessageReceivedListRequest) throws java.rmi.RemoteException, org.openimmunizationsoftware.dqa.service.client.FaultType;
    public org.openimmunizationsoftware.dqa.service.client.GetMessageReceivedDetailsResultType getMessageReceivedDetails(org.openimmunizationsoftware.dqa.service.client.GetMessageReceivedDetailsType getMessageReceivedDetailsRequest) throws java.rmi.RemoteException, org.openimmunizationsoftware.dqa.service.client.FaultType;
    public org.openimmunizationsoftware.dqa.service.client.GetPatientResultType getPatient(org.openimmunizationsoftware.dqa.service.client.GetPatientType getPatientRequest) throws java.rmi.RemoteException, org.openimmunizationsoftware.dqa.service.client.FaultType;
    public org.openimmunizationsoftware.dqa.service.client.GetVaccinationListResultType getVaccinationList(org.openimmunizationsoftware.dqa.service.client.GetVaccinationListType getVaccinationListRequest) throws java.rmi.RemoteException, org.openimmunizationsoftware.dqa.service.client.FaultType;
    public org.openimmunizationsoftware.dqa.service.client.GetNextOfKinListResultType getNextOfKinList(org.openimmunizationsoftware.dqa.service.client.GetNextOfKinListType getNextOfKinListRequest) throws java.rmi.RemoteException, org.openimmunizationsoftware.dqa.service.client.FaultType;
}
